package org.mycard.smartcard.pcscWrapper.helpers;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import javax.smartcardio.ResponseAPDU;
import java.util.HashMap;
import java.util.Map;

import static org.mycard.common.ByteArrayHelper.hex;


public class ErrorCodes {
    final private static Logger log = LoggerFactory.getLogger(ErrorCodes.class);


    private static Map<String, String> codeToMsg = new HashMap<>();

    static {
        addError("6 ", " 	", "E	 ", "   Class not supported.");
        addError("  ", "  ", "   61", "	--	I	Response bytes still available                                                                                                      ");
        addError("61", "XX", "	I", "	Command successfully executed; 'XX' bytes of data are available and can be requested using GET RESPONSE.                                    ");
        addError("  ", "  ", "   62", "	--	W	State of non-volatile memory unchanged                                                                                              ");
        addError("62", "00", "	W", "	No information given (NV-Ram not changed)                                                                                                   ");
        addError("62", "01", "	W", "	NV-Ram not changed 1.                                                                                                                       ");
        addError("  ", "  ", "   62", "	81	W	Part of returned data may be corrupted                                                                                              ");
        addError("62", "82", "	W", "	End of file/record reached before reading Le bytes                                                                                          ");
        addError("62", "83", "	W", "	Selected file invalidated                                                                                                                   ");
        addError("62", "84", "	W", "	Selected file is not valid. FCI not formated according to ISO                                                                               ");
        addError("62", "85", "	W", "	No Purse Engine enslaved for R3bc                                                                                                           ");
        addError("62", "A2", "	W", "	Wrong R-MAC                                                                                                                                 ");
        addError("62", "A4", "	W", "	Card locked (during reset( ))                                                                                                               ");
        addError("  ", "  ", "   62", "	CX	W	Counter with value x (command dependent)                                                                                            ");
        addError("62", "F1", "	W", "	Wrong C-MAC                                                                                                                                 ");
        addError("62", "F3", "	W", "	Internal reset                                                                                                                              ");
        addError("62", "F5", "	W", "	Default agent locked                                                                                                                        ");
        addError("62", "F7", "	W", "	Cardholder locked                                                                                                                           ");
        addError("62", "F8", "	W", "	Basement is current agent                                                                                                                   ");
        addError("62", "F9", "	W", "	CALC Key Set not unblocked                                                                                                                  ");
        addError("62", "FX", "	W", "	-                                                                                                                                           ");
        addError("  ", "  ", "   62", "	XX	W	RFU                                                                                                                                 ");
        addError("63", "--", "	W", "	State of non-volatile memory changed                                                                                                        ");
        addError("63", "00", "	W", "	No information given (NV-Ram changed)                                                                                                       ");
        addError("63", "81", "	W", "	File filled up by the last write. Loading/updating is not allowed.                                                                          ");
        addError("  ", "  ", "   63", "	82	W	Card key not supported.                                                                                                             ");
        addError("63", "83", "	W", "	Reader key not supported.                                                                                                                   ");
        addError("63", "84", "	W", "	Plaintext transmission not supported.                                                                                                       ");
        addError("63", "85", "	W", "	Secured transmission not supported.                                                                                                         ");
        addError("63", "86", "	W", "	Volatile memory is not available.                                                                                                           ");
        addError("  ", "  ", "   63", "	87	W	Non-volatile memory is not available.                                                                                               ");
        addError("  ", "  ", "   63", "	88	W	Key number not valid.                                                                                                               ");
        addError("63", "89", "	W", "	Key length is not correct.                                                                                                                  ");
        addError("  ", "  ", "   63", "	C0	W	Verify fail, no try left.                                                                                                           ");
        addError("63", "C1", "	W", "	Verify fail, 1 try left.                                                                                                                    ");
        addError("63", "C2", "	W", "	Verify fail, 2 tries left.                                                                                                                  ");
        addError("  ", "  ", "   63", "	C3	W	Verify fail, 3 tries left.                                                                                                          ");
        addError("  ", "  ", "   63", "	CX	W	Counter with value x (command dependent)                                                                                            ");
        addError("63", "FX", "	W", "	-                                                                                                                                           ");
        addError("  ", "  ", "   63", "	XX	W	RFU                                                                                                                                 ");
        addError("64", "--", "	E", "	State of non-volatile memory unchanged                                                                                                      ");
        addError("64", "00", "	E", "	No information given (NV-Ram not changed)                                                                                                   ");
        addError("64", "01", "	E", "	Command timeout.                                                                                                                            ");
        addError("64", "XX", "	E", "	RFU                                                                                                                                         ");
        addError("65", "--", "	E", "	State of non-volatile memory changed                                                                                                        ");
        addError("65", "00", "	E", "	No information given                                                                                                                        ");
        addError("65", "01", "	E", "	Write error. Memory failure. There have been problems in writing or reading the EEPROM. Other hardware problems may also bring this error.  ");
        addError("65", "81", "	E", "	Memory failure                                                                                                                              ");
        addError("65", "FX", "	E", "	-                                                                                                                                           ");
        addError("  ", "  ", "   65", "	XX	E	RFU                                                                                                                                 ");
        addError("66", "--", "	S", "                                                                                                                                               ");
        addError("66", "69", "	S", "	Incorrect Encryption/Decryption Padding                                                                                                     ");
        addError("66", "XX", "	S", "	-                                                                                                                                           ");
        addError("  ", "  ", "   67", "	--	E                                                                                                                                       ");
        addError("67", "00", "	E", "	Wrong length                                                                                                                                ");
        addError("67", "XX", "	E", "	length incorrect (procedure)(ISO 7816-3)                                                                                                    ");
        addError("  ", "  ", "   68", "	--	E	Functions in CLA not supported                                                                                                      ");
        addError("68", "00", "	E", "	No information given (The request function is not supported by the card)                                                                    ");
        addError("68", "81", "	E", "	Logical channel not supported                                                                                                               ");
        addError("68", "82", "	E", "	Secure messaging not supported                                                                                                              ");
        addError("68", "83", "	E", "	Last command of the chain expected                                                                                                          ");
        addError("68", "84", "	E", "	Command chaining not supported                                                                                                              ");
        addError("68", "FX", "	E", "	-                                                                                                                                           ");
        addError("  ", "  ", "   68", "	XX	E	RFU                                                                                                                                 ");
        addError("69", "--", "	E", "	Command not allowed                                                                                                                         ");
        addError("69", "00", "	E", "	No information given (Command not allowed)                                                                                                  ");
        addError("69", "81", "	E", "	Command incompatible with file structure                                                                                                    ");
        addError("69", "82", "	E", "	Security condition not satisfied.                                                                                                           ");
        addError("69", "83", "	E", "	Authentication method blocked                                                                                                               ");
        addError("69", "84", "	E", "	Referenced data reversibly blocked (invalidated)                                                                                            ");
        addError("69", "85", "	E", "	Conditions of use not satisfied                                                                                                             ");
        addError("69", "86", "	E", "	Command not allowed (no current EF)                                                                                                         ");
        addError("69", "87", "	E", "	Expected secure messaging (SM) object missing                                                                                               ");
        addError("69", "88", "	E", "	Incorrect secure messaging (SM) data object                                                                                                 ");
        addError("69", "96", "	E", "	Data must be updated again                                                                                                                  ");
        addError("69", "F0", "	E", "	Permission Denied                                                                                                                           ");
        addError("69", "F1", "	E", "	Permission Denied - Missing Privilege                                                                                                       ");
        addError("69", "FX", "	E", "	-                                                                                                                                           ");
        addError("  ", "  ", "   69", "	XX	E	RFU                                                                                                                                 ");
        addError("6A", "--", "	E", "	Wrong parameter(s) P1-P2                                                                                                                    ");
        addError("6A", "00", "	E", "	No information given (Bytes P1 and/or P2 are incorrect)                                                                                     ");
        addError("6A", "02", "	E", "	Incoming total bet sum for client applet is greater than client balance                                                                     ");
        addError("6A", "03", "	E", "	Invalid incoming balance, bet sum or bet sum limit for client applet (check whether it's > 0)                                               ");
        addError("6A", "04", "	E", "	Not all games are loaded during client applet personalization                                                                               ");
        addError("6A", "07", "	E", "	Invalid number of spins for client applet (check whether it's > 15)                                                                         ");
        addError("6A", "08", "	E", "   There is lack of memory for bets history array, decrease the number of spins!                                                               ");
        addError("6A", "09", "	E", "	Invalid game number                                                                                                                         ");
        addError("6A", "0A", "	E", "	No more spins                                                                                                                               ");
        addError("6A", "0B", "	E", "	Negative offset in history record (check whether it's > 0)                                                                                  ");
        addError("6A", "0C", "	E", "	Bet sum limit is exceeded                                                                                                                   ");
        addError("6A", "11", "	E", "	Invalid incoming number of spins for admin applet (check whether it's > 0)                                                                  ");
        addError("6A", "12", "	E", "	Incoming number of spins is larger than GAME_CNT counter in admin applet                                                                    ");
        addError("6A", "13", "	E", "	Invalid incoming balance for admin applet (check whether it's > 0)                                                                          ");
        addError("6A", "80", "	E", "	The parameters in the data field are incorrect.                                                                                             ");
        addError("6A", "81", "	E", "	Function not supported                                                                                                                      ");
        addError("6A", "82", "	E", "	File not found                                                                                                                              ");
        addError("6A", "83", "	E", "	Record not found                                                                                                                            ");
        addError("6A", "84", "	E", "	There is insufficient memory space in record or file                                                                                        ");
        addError("6A", "85", "	E", "	Lc inconsistent with TLV structure                                                                                                          ");
        addError("6A", "86", "	E", "	Incorrect P1 or P2 parameter.                                                                                                               ");
        addError("  ", "  ", "   6A", "	87	E	Lc inconsistent with P1-P2                                                                                                          ");
        addError("6A", "88", "	E", "	Referenced data not found                                                                                                                   ");
        addError("6A", "89", "	E", "	File already exists                                                                                                                         ");
        addError("6A", "8A", "	E", "	DF name already exists.                                                                                                                     ");
        addError("  ", "  ", "   6A", "	F0	E	Wrong parameter value                                                                                                               ");
        addError("6A", "FX", "	E", "	-                                                                                                                                           ");
        addError("  ", "  ", "   6A", "	XX	E	RFU                                                                                                                                 ");
        addError("6B", "--", "	E", "                                                                                                                                               ");
        addError("6B", "00", "	E", "	Wrong parameter(s) P1-P2                                                                                                                    ");
        addError("6B", "XX", "	E", "	Reference incorrect (procedure byte), (ISO 7816-3)                                                                                          ");
        addError("  ", "  ", "   6C", "	--	E	Wrong length Le                                                                                                                     ");
        addError("6C", "00", "	E", "	Incorrect P3 length.                                                                                                                        ");
        addError("  ", "  ", "   6C", "	XX	E	xx = exact Le                                                                                                                       ");
        addError("6D", "--", "	E", "                                                                                                                                               ");
        addError("6D", "00", "	E", "	Instruction code not supported or invalid                                                                                                   ");
        addError("6D", "XX", "	E", "	Instruction code not programmed or invalid (procedure byte), (ISO 7816-3)                                                                   ");
        addError("  ", "  ", "   6E", "	--	E                                                                                                                                       ");
        addError("6E", "00", "	E", "	Class not supported                                                                                                                         ");
        addError("6E", "XX", "	E", "	Instruction class not supported (procedure byte), (ISO 7816-3)                                                                              ");
        addError("  ", "  ", "   6F", "	--	E	Internal exception                                                                                                                  ");
        addError("6F", "00", "	E", "	Command aborted - more exact diagnosis not possible (e.g., operating system error).                                                         ");
        addError("  ", "  ", "   6F", "	FF	E	Card dead (overuse, …)                                                                                                              ");
        addError("6F", "XX", "	E", "	No precise diagnosis (procedure byte), (ISO 7816-3)                                                                                         ");
        addError("  ", "  ", "   9-", "	--                                                                                                                                          ");
        addError("  ", "  ", "   90", "	00	I	Command successfully executed (OK).                                                                                                 ");
        addError("  ", "  ", "   90", "	04	W	PIN not succesfully verified, 3 or more PIN tries left                                                                              ");
        addError("90", "08", "	 ", "	Key/file not found                                                                                                                          ");
        addError("90", "80", "	W", "	Unblock Try Counter has reached zero                                                                                                        ");
        addError("91", "01", "	 ", "	States.activity, States.lock Status or States.lockable has wrong value                                                                      ");
        addError("91", "02", "	 ", "	Transaction number reached its limit                                                                                                        ");
        addError("92", "10", "	E", "	No more storage available.                                                                                                                  ");
        addError("93", "01", "	 ", "	Integrity error                                                                                                                             ");
        addError("93", "02", "	 ", "	Candidate S2 invalid                                                                                                                        ");
        addError("94", "01", "	 ", "	Candidate currency code does not match purse currency                                                                                       ");
        addError("94", "02", "	 ", "	Candidate amount too high                                                                                                                   ");
        addError("94", "03", "	 ", "	Candidate amount too low                                                                                                                    ");
        addError("94", "05", "	 ", "	Problems in the data field                                                                                                                  ");
        addError("94", "07", "	 ", "	Bad currency : purse engine has no slot with R3bc currency                                                                                  ");
        addError("94", "08", "	 ", "	R3bc currency not supported in purse engine                                                                                                 ");
        addError("95", "80", "	 ", "	Bad sequence                                                                                                                                ");
        addError("96", "81", "	 ", "	Slave not found                                                                                                                             ");
        addError("97", "00", "	 ", "	PIN blocked and Unblock Try Counter is 1 or 2                                                                                               ");
        addError("  ", "  ", "   97", "	02	 	Main keys are blocked                                                                                                               ");
        addError("97", "04", "	 ", "	PIN not succesfully verified, 3 or more PIN tries left                                                                                      ");
        addError("97", "84", "	 ", "	Base key                                                                                                                                    ");
        addError("97", "85", "	 ", "	Limit exceeded - C-MAC key                                                                                                                  ");
        addError("97", "86", "	 ", "	SM error - Limit exceeded - R-MAC key                                                                                                       ");
        addError("97", "87", "	 ", "	Limit exceeded - sequence counter                                                                                                           ");
        addError("97", "88", "	 ", "	Limit exceeded - R-MAC length                                                                                                               ");
        addError("97", "89", "	 ", "	Service not available                                                                                                                       ");
        addError("98", "04", "	E", "	Access conditions not satisfied.                                                                                                            ");
        addError("99", "00", "	 ", "	1 PIN try left                                                                                                                              ");
        addError("99", "04", "	 ", "	PIN not succesfully verified, 1 PIN try left                                                                                                ");
        addError("99", "85", "	 ", "	Wrong status - Cardholder lock                                                                                                              ");
        addError("99", "86", "	E", "	Missing privilege                                                                                                                           ");
        addError("99", "87", "	 ", "	PIN is not installed                                                                                                                        ");
        addError("99", "88", "	 ", "	Wrong status - R-MAC state                                                                                                                  ");
        addError("9A", "00", "	 ", "	2 PIN try left                                                                                                                              ");
        addError("9A", "04", "	 ", "	PIN not succesfully verified, 2 PIN try left                                                                                                ");
        addError("9A", "71", "	 ", "	Wrong parameter value - Double agent AID                                                                                                    ");
        addError("9A", "72", "	 ", "	Wrong parameter value - Double agent Type                                                                                                   ");
        addError("9D", "05", "	E", "	Incorrect certificate type                                                                                                                  ");
        addError("9D", "07", "	E", "	Incorrect session data size                                                                                                                 ");
        addError("9D", "08", "	E", "	Incorrect DIR file record size                                                                                                              ");
        addError("9D", "09", "	E", "	Incorrect FCI record size                                                                                                                   ");
        addError("9D", "0A", "	E", "	Incorrect code size                                                                                                                         ");
        addError("9D", "10", "	E", "	Insufficient memory to load application                                                                                                     ");
        addError("9D", "11", "	E", "	Invalid AID                                                                                                                                 ");
        addError("9D", "12", "	E", "	Duplicate AID                                                                                                                               ");
        addError("9D", "13", "	E", "	Application previously loaded                                                                                                               ");
        addError("9D", "14", "	E", "	Application history list full                                                                                                               ");
        addError("9D", "15", "	E", "	Application not open                                                                                                                        ");
        addError("9D", "17", "	E", "	Invalid offset                                                                                                                              ");
        addError("9D", "18", "	E", "	Application already loaded                                                                                                                  ");
        addError("9D", "19", "	E", "	Invalid certificate                                                                                                                         ");
        addError("9D", "1A", "	E", "	Invalid signature                                                                                                                           ");
        addError("9D", "1B", "	E", "	Invalid KTU                                                                                                                                 ");
        addError("9D", "1D", "	E", "	MSM controls not set                                                                                                                        ");
        addError("9D", "1E", "	E", "	Application signature does not exist                                                                                                        ");
        addError("9D", "1F", "	E", "	KTU does not exist                                                                                                                          ");
        addError("9D", "20", "	E", "	Application not loaded                                                                                                                      ");
        addError("9D", "21", "	E", "	Invalid Open command data length                                                                                                            ");
        addError("9D", "30", "	E", "	Check data parameter is incorrect (invalid start address)                                                                                   ");
        addError("9D", "31", "	E", "	Check data parameter is incorrect (invalid length)                                                                                          ");
        addError("9D", "32", "	E", "	Check data parameter is incorrect (illegal memory check area)                                                                               ");
        addError("9D", "40", "	E", "	Invalid MSM Controls ciphertext                                                                                                             ");
        addError("9D", "41", "	E", "	MSM controls already set                                                                                                                    ");
        addError("9D", "42", "	E", "	Set MSM Controls data length less than 2 bytes                                                                                              ");
        addError("9D", "43", "	E", "	Invalid MSM Controls data length                                                                                                            ");
        addError("9D", "44", "	E", "	Excess MSM Controls ciphertext                                                                                                              ");
        addError("9D", "45", "	E", "	Verification of MSM Controls data failed                                                                                                    ");
        addError("9D", "50", "	E", "	Invalid MCD Issuer production ID                                                                                                            ");
        addError("9D", "51", "	E", "	Invalid MCD Issuer ID                                                                                                                       ");
        addError("9D", "52", "	E", "	Invalid set MSM controls data date                                                                                                          ");
        addError("9D", "53", "	E", "	Invalid MCD number                                                                                                                          ");
        addError("9D", "54", "	E", "	Reserved field error                                                                                                                        ");
        addError("9D", "55", "	E", "	Reserved field error                                                                                                                        ");
        addError("9D", "56", "	E", "	Reserved field error                                                                                                                        ");
        addError("9D", "57", "	E", "	Reserved field error                                                                                                                        ");
        addError("9D", "60", "	E", "	MAC verification failed                                                                                                                     ");
        addError("9D", "61", "	E", "	Maximum number of unblocks reached                                                                                                          ");
        addError("9D", "62", "	E", "	Card was not blocked                                                                                                                        ");
        addError("9D", "63", "	E", "	Crypto functions not available                                                                                                              ");
        addError("9D", "64", "	E", "	No application loaded                                                                                                                       ");
        addError("9E", "00", "	 ", "	PIN not installed                                                                                                                           ");
        addError("9E", "04", "	 ", "	PIN not succesfully verified, PIN not installed                                                                                             ");
        addError("9F", "00", "	 ", "	PIN blocked and Unblock Try Counter is 3                                                                                                    ");
        addError("9F", "04", "	 ", "	PIN not succesfully verified, PIN blocked and Unblock Try Counter is 3                                                                      ");
        addError("9x", "XX", "	 ", "	Application related status, (ISO 7816-3)                                                                                                    ");
    }


    private static void addError(String sw1, String sw2, String type, String s) {
        codeToMsg.put(sw1 + sw2, s.trim());
    }



    public static Object getMsg(ResponseAPDU apduAnswer) {
        byte[] sw = {(byte) apduAnswer.getSW1(), (byte) apduAnswer.getSW2()};
        String swFormatted = hex(sw);
        return codeToMsg.get(swFormatted);
    }

}
